### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by hannesa2**
It's just a demonstration what I did

### CODE REVIEW

**Comment by hannesa2** [comment]
Because there was some noise in the commit, I removed the comments to make it clear what happens

**Comment by hannesa2** [comment]
Without "cameraX" I run now into 
image

**Comment by abhishekk06** [comment]
This I am not sure of. Let me also pull and check. As per the comment in
the original thread
<https://github.com/google-ar/arcore-android-sdk/issues/1210>, things
should just work fine if we move away from CameraX.

[image: image.png]

**Comment by abhishekk06** [comment]
This is what I ran into when I try to compile branch "cameraX" and run it on my device. I guess we are still having a shared session somewhere but not sure how to proceed with this debug. Any suggestion?  

image

**Comment by hannesa2** [comment]
Now I see 
* first nothing
* lock screen
* unlock screen
* **I see camera preview !** 👍 
* crash after a view seconds with 
image

... I'm off for today

**Comment by abhishekk06** [comment]
https://github.com/google-ar/arcore-android-sdk/issues/1181

Looks like we are calling session.update() from the non-GL thread. Do you have any suggestions on how to fix that issue?

**Pull request merged**
